version: '3.3'

services:
  app:
    image: brick-node-app
    build: .
    environment:
      - UUID=${UUID}
    ports:
      - "8000-8002:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/hostname"]
      interval: 10s
      timeout: 5s
      retries: 3